class CreateLocalizations < ActiveRecord::Migration
  def change
    create_table :localizations do |t|
    	t.string :localization
    	t.string :fieldName
    	t.string :value
      t.timestamps
    end

    execute "INSERT INTO localizations
	(localization, fieldName, value)
VALUES
	('pl-pl', 'languageName', 'Polski'),
	('en-us', 'languageName', 'English'),
	('pl-pl', 'loginError', 'Podałeś nieprawidłowe dane!'),
	('en-us', 'loginError', 'You have entered wrong credentials!'),
    ('pl-pl', 'loginButton', 'Zaloguj'),
	('en-us', 'loginButton', 'Login'),
    ('pl-pl', 'rememberMe', 'Zapamiętaj mnie'),
	('en-us', 'rememberMe', 'Remember me'),
    ('pl-pl', 'email', 'Email'),
	('en-us', 'email', 'Email'),
    ('pl-pl', 'password', 'Hasło'),
	('en-us', 'password', 'Password'),
    ('pl-pl', 'loginChangePassword', 'Nie pamiętasz hasła?'),
	('en-us', 'loginChangePassword', 'Forgot your password?'),
    ('pl-pl', 'loginPageSlogan', 'Poznaj nowych przyjaciół z całego świata!'),
	('en-us', 'loginPageSlogan', 'Meet new friends from all around of the world!'),
    ('pl-pl', 'loginAddNewAccount', 'Załóż nowe konto'),
	('en-us', 'loginAddNewAccount', 'Create a new account'),
	('pl-pl', 'languageSelectBoxLabel', 'Zmień język'),
	('en-us', 'languageSelectBoxLabel', 'Change language'),
	('pl-pl', 'firstName', 'Imię'),
	('en-us', 'firstName', 'First name'),
	('pl-pl', 'lastName', 'Nazwisko'),
	('en-us', 'lastName', 'Last name'),
	('pl-pl', 'passwordRepeated', 'Powtórz hasło'),
	('en-us', 'passwordRepeated', 'Repeat password'),
	('pl-pl', 'registerButton', 'Zarejestruj'),
	('en-us', 'registerButton', 'Register'),
	('pl-pl', 'registrationError', 'Już istnieje użytkownik o tym adresie email!'),
	('en-us', 'registrationError', 'User for given address email already exist!'),
	('pl-pl', 'serverUnaviable', 'Nie można połączyć się z serwerem, spróbuj ponownie póniej.'),
	('en-us', 'serverUnaviable', 'Cannot connect to remote server, please try again later.'),
	('pl-pl', 'birthdate', 'Data urodzenia'),
	('en-us', 'birthdate', 'Birth date'),
	('pl-pl', 'confirmationSuccess', 'Twoja rejestracja została potwierdzona!'),
	('en-us', 'confirmationSuccess', 'Your registration was confirmed!'),
	('pl-pl', 'confirmationFailure', 'Twoja rejestracja została już potwierdzona lub link potwierdzający wygasł! W razie wygaśnięcia linku, zarejestruj się ponownie.'),
	('en-us', 'confirmationFailure', 'Your registration is already confirmed or confirmation link expired! If your confirmation linki expired you need to register again.'),
	('pl-pl', 'confirmationEmail', 'Dziękujemy za rejestracje w serwisie TalkToMe!\nŻeby potwierdzić swoją rejestrację kliknij w poniższy link:\n\n%s\n\nJeżeli nie rejestrowałeś się w naszym portalu to zignoruj ten email.'),
	('en-us', 'confirmationEmail', 'Thank you for your registration in TalkToMe!\nTo confirm your registration click below link:\n\n%s\n\nIf you have not registered in our service then ignore this email.'),
	('pl-pl', 'registrationSuccess', 'Rejestracja powiodła się! Przejdź do swojej skrzynki pocztowej i potwierdź rejestracje.'),
	('en-us', 'registrationSuccess', 'Registration succeeded!! Go to your mail box and confirm your registration.'),
	('pl-pl', 'confirmationEmailSubject', 'Potwierdzenie rejestracji'),
	('en-us', 'confirmationEmailSubject', 'Confirmation of registration'),
	('pl-pl', 'changePasswordButton', 'Zmień'),
	('en-us', 'changePasswordButton', 'Change'),
	('pl-pl', 'changePasswordEmail', 'Aby zmienić hasło kliknij na poniższy link:\n\n%s\n\nJeśli nie chcesz zmieniać hasła zignoruj tę wiadomość.'),
	('en-us', 'changePasswordEmail', 'To change password clik link below:\n\n%s\n\nIf you are no longer intrested in changing password then ignore this message.'),
	('pl-pl', 'changePasswordEmailSubject', 'Zmiana hasła'),
	('en-us', 'changePasswordEmailSubject', 'Change password'),
	('pl-pl', 'changePasswordCodeGenerationInfo', 'Podaj adres email którego użyłeś podczas rejestracji:'),
	('en-us', 'changePasswordCodeGenerationInfo', 'Insert email address which was used during registration:'),
	('pl-pl', 'changePasswordInfo', 'Podaj nowe hasło:'),
	('en-us', 'changePasswordInfo', 'Insert new password:'),
	('pl-pl', 'changePasswordSuccess', 'Hasło zostało zmienione! Zachwile zostaniesz przekierowany do strony logowania.'),
	('en-us', 'changePasswordSuccess', 'Password has changed! In few seconds you will be redirected to login page.'),
	('pl-pl', 'changePasswordFailure', 'Zmiana hasła nie powiodłą się, spróbuj ponownie pónźiej'),
	('en-us', 'changePasswordFailure', 'Changing password failed, try again later.'),
	('pl-pl', 'codeGenerationSuccess', 'Link do zmiany hasła został wysłany na twoją skrzynke pocztową.'),
	('en-us', 'codeGenerationSuccess', 'Link for changing password was sent to your email box.'),
	('pl-pl', 'codeGenerationFailure', 'Generowanie linku do zmiany hasła nie powiodło się, spróbuj ponownie póniej.'),
	('en-us', 'codeGenerationFailure', 'Generating link for password change failed, try again later.'),
	('pl-pl', 'topMenuProfile', 'Profil'),
	('en-us', 'topMenuProfile', 'Profile'),
	('pl-pl', 'topMenuFind', 'Szukaj znajomych'),
	('en-us', 'topMenuFind', 'Find friends'),
	('pl-pl', 'topMenuConversation', 'Rozmowa'),
	('en-us', 'topMenuConversation', 'Conversation'),
	('pl-pl', 'topMenuFriends', 'Znajomi'),
	('en-us', 'topMenuFriends', 'Friends'),
	('pl-pl', 'logout', 'Wyloguj'),
	('en-us', 'logout', 'Logout'),
	('pl-pl', 'telephone', 'Telefon'),
	('en-us', 'telephone', 'Telephone'),
	('pl-pl', 'chooseCountries', 'Wybierz kraje'),
	('en-us', 'chooseCountries', 'Choose countries'),
	('pl-pl', 'chooseInterests', 'Wybierz zainteresowania'),
	('en-us', 'chooseInterests', 'Choose interests'),
	('pl-pl', 'aboutMe', 'O mnie'),
	('en-us', 'aboutMe', 'About me'),
	('pl-pl', 'aboutMeMsg', 'Napisz coś o sobie...'),
	('en-us', 'aboutMeMsg', 'Write something about yourself...'),
	('pl-pl', 'lookingForCountries', 'Szukam znajomości z'),
	('en-us', 'lookingForCountries', 'I am looking for friends from'),
	('pl-pl', 'myInterests', 'Moje zainteresowania'),
	('en-us', 'myInterests', 'My interests'),
	('pl-pl', 'contact', 'Kontakt'),
	('en-us', 'contact', 'Contact'),
	('pl-pl', 'defaultSearchSettingsMsg', 'Szukaj znajomych z domyślnymi ustawieniami'),
	('en-us', 'defaultSearchSettingsMsg', 'Search friends with default search settings'),
	('pl-pl', 'modifiedSearchSettingsMsg', 'Szukaj znajomych z modifikowanymi ustawieniami'),
	('en-us', 'modifiedSearchSettingsMsg', 'Search friends with modified search settings'),
	('pl-pl', 'change', 'Zmień'),
	('en-us', 'change', 'Change'),
	('pl-pl', 'changeSearchSettings', 'Użyj tych ustawień'),
	('en-us', 'changeSearchSettings', 'Use this settings'),
	('pl-pl', 'cancel', 'Anuluj'),
	('en-us', 'cancel', 'Cancel'),
	('pl-pl', 'fromCountries', 'Pochodzących z'),
	('en-us', 'fromCountries', 'From'),
	('pl-pl', 'interestedIn', 'Interesujących się'),
	('en-us', 'interestedIn', 'Interested in'),
	('pl-pl', 'inAge', 'W wieku'),
	('en-us', 'inAge', 'In age'),
	('pl-pl', 'men', 'Mężczyzn'),
	('en-us', 'men', 'Men'),
	('pl-pl', 'women', 'Kobiety'),
	('en-us', 'women', 'Women'),
	('pl-pl', 'sex', 'Płeć'),
	('en-us', 'sex', 'Sex'),
	('pl-pl', 'age', 'Wiek'),
	('en-us', 'age', 'Age'),
	('pl-pl', 'back', 'Wstecz'),
	('en-us', 'back', 'Back'),
	('pl-pl', 'wordForTranslation', 'Słowo do tłumaczenia'),
	('en-us', 'wordForTranslation', 'Word for translation'),
	('pl-pl', 'translation', 'Tłumaczenie'),
	('en-us', 'translation', 'Translation'),
	('pl-us', 'message', 'Wiadomość'),
	('en-us', 'message', 'Message'),
	('pl-pl', 'search', 'Szukaj'),
	('en-us', 'search', 'Search'),
	('pl-pl', 'invertLanguages', 'Odwróć'),
	('en-us', 'invertLanguages', 'Invert'),
	('pl-pl', 'addToFriendList', 'Dodaj do znajomych'),
	('en-us', 'addToFriendList', 'Add to friend list'),
	('pl-pl', 'poland', 'Polska'),
	('en-us', 'poland', 'Poland'),
	('pl-pl', 'USA', 'Stany zjednoczone'),
	('en-us', 'USA', 'United states of America'),
	('pl-pl', 'save', 'Zapisz'),
	('en-us', 'save', 'Save'),
	('pl-pl', 'deleteFromFriends', 'Usuń ze znajomych'),
	('en-us', 'deleteFromFriends', 'Delete from friend list'),
	('pl-pl', 'confirmFriend', 'Potwierdź'),
	('en-us', 'confirmFriend', 'Confirm'),
	('pl-pl', 'rejectFriend', 'Odrzuć'),
	('en-us', 'rejectFriend', 'Reject'),
	('pl-pl', 'changeProfilePicture', 'Zmień zdjęcie profilowe'),
	('en-us', 'changeProfilePicture', 'Change profile picture'),
	('pl-pl', 'confirmed', 'Potwierdzeni'),
	('en-us', 'confirmed', 'Confirmed'),
	('pl-pl', 'unconfirmed', 'Nie potwierdzeni'),
	('en-us', 'unconfirmed', 'Unconfirmed');"
  end
end
